### ISSUE TITLE
Restful API example 

### ISSUE THREAD

**Issue by liufei11111** [karenyang/pluginless_agent_with_graphql#3]
Hi, I am evaluating this app to automate some of tasks. I really love your beautiful code and your thoughtfulness in putting this all together. Those are just amazing. My observation is that graphQL is harder to read and I get used to using Flask or some RESTful API frameworks. I found it easier to use. Do you mind offering some alternative in RESTful design as well?
I hope that this could be a trusted and reliable open source project where AI enthusiasts like you and me can work together on meaningful things together. Look forward to your updates!

**Comment by liufei11111** [comment]
Given that this project is so lovely and ubiquitous, I personally would want to contribute as well. Do you mind adding me as a contributor so that I can submit pull requests?
My plan is to add a Flask demo code repo and add some html and JS modules to visualize the result and this one can be embedded into my other hackathon projects as a component. Would love to hear from you! @karenyang

**Comment by liufei11111** [comment]
Also, do you mind making this project an Apache 2 licensed project with a license file like here https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by kenhuangus** [comment]
I love the code and the idea of plug-in less agents. I believe this should be how the future of GPT-based workflow should operate @karenyang . I do have one suggestion: you can use git secret to store the bearer token for authorization for Yelp API instead of hard-code it in the demo.py.
