### ISSUE TITLE
gpt-4 non-existence 

### ISSUE THREAD

**Issue by liufei11111** [karenyang/pluginless_agent_with_graphql#4]
Hi, thanks for the demo. I am seeing chatgpt-4 non-existence error as in the screenshot running on MacOS with python3.11. 

A note for mac is that I have to install `graphql-core`, `graphene`, `cython` as well.

![Screenshot 2023-04-17 at 5 47 37 PM](https://user-images.githubusercontent.com/4622463/232640612-7c4ba2d3-d10a-43bb-a15b-9b6c4f598756.png)

It looks that the model as in this introduction works https://platform.openai.com/docs/guides/chat/introduction. The model is `gpt-3.5-turbo`

**Comment by karenyang** [comment]
You will need gpt-4 access in your openai account in order to use that model.  You can replace the gpt-4 model with gpt-3.5-turbo and see whether it works? It might not have the desired result and the context size will be smaller (4k instead of 8k)

**Comment by liufei11111** [comment]
Fabulous! That is exactly what I need. Closing for now. Thanks.
